worker_processes auto;
events { worker_connections 1024; }

http {
    sendfile on;

    upstream fastapi {
        server 127.0.0.1:8000;
    }

    upstream streamlit {
        server 127.0.0.1:8501;
    }

    server {
        listen 8080;

        # Streamlit (par défaut)
        location / {
            proxy_pass http://streamlit;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # FastAPI sous /api
        location /api {
            proxy_pass http://fastapi;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
